### ISSUE TITLE
Publish new npm release

### ISSUE THREAD

**Issue by chrisbrown-io** [langbamit/svelte-scrollto#4]
I fixed an issue (#1 / #2 / #3 ) in a PR that you merged, much appreciated. 

It would be great if you could publish a new version to npm, so everyone using this package (me included) can benefit from installing directly from there. I've just been installing the latest commit from github via npm in the meantime.

Thanks for the great work on the lib!

**Comment by utherpally** [comment]
Thanks for reminding me. I'm published svelte-scrollto@0.2.0 on npm.
